mysql:
  path: 127.0.0.1:3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: gva
  username: root
  password: "123456"
  max-idle-conns: 0
  max-open-conns: 0
  log-mode: ""
  log-zap: false


system:
  env: public
  addr: 8888
  db-type: mysql
  oss-type: local
  use-multipoint: false
